# Generated by Django 5.0.4 on 2024-06-02 01:34

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_compare_at_price_product_cost_product_margin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('blog', models.CharField(max_length=150, verbose_name=api.models.Blog)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogauthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
