# Generated by Django 5.0.4 on 2024-06-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blogpost_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
